# Device config
esphome:
  name: accelerometers
  friendly_name: Accelerometers

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# ESPHome boilerplate
logger:
  level: DEBUG
  logs:
    sensor: INFO
api:
wifi:
  networks: !secret wifi
ota:
  - platform: esphome
    password: !secret ota_password

# Everything else
sensor:
  - platform: internal_temperature
    name: "CPU temperature"
  - platform: wifi_signal
    name: "Signal strength"
    update_interval: 60s
  - platform: bmi160
    address: 0x69
    update_interval: 1s
    acceleration_x:
      name: "Accelerometer 1 X"
    acceleration_y:
      name: "Accelerometer 1 Y"
    acceleration_z:
      name: "Accelerometer 1 Z"
  - platform: bmi160
    address: 0x68
    update_interval: 1s
    acceleration_x:
      name: "Accelerometer 2 X"
    acceleration_y:
      name: "Accelerometer 2 Y"
    acceleration_z:
      name: "Accelerometer 2 Z"

i2c:
  sda: 21
  scl: 22

text_sensor:
  - platform: wifi_info
    ssid:
      name: SSID
      entity_category: diagnostic
